// Independent AgentLair run of the aeoess round 1 receipt vectors.
//
// The run happened on 2026-08-05 and was reported in mail. Mail is not evidence
// anyone can replay, so the report lives here instead, and the runner that
// produced it ships beside it — a report nobody can regenerate is a claim.
//
// Nothing here imports the SDK that emitted the vectors, and nothing imports
// runners/aeoess_receipt_runner.py. Every construction is reimplemented from the
// profile text in SOURCE.md:
//
//   receipt_id  SHA-256(ASCII("APS-RECEIPT-ID-V1") || 0x00 ||
//                       UTF8(JCS(receipt without receipt_id and signatures)))
//   signature   Ed25519 over ASCII("APS-RECEIPT-SIG-V1") || 0x00 ||
//                       UTF8(JCS({"receipt": receipt without signatures,
//                                 "signer": {signer, key_id, alg}}))
//   chain root  SHA-256(UTF8(JCS(chain))). Bare: no tag, no separator byte.
//   integrity   receipt_len / receipt_sha256 over the compact serialization in
//               the member order as published
//
// Two verdicts per vector. `theirs` is this profile's order — schema, receipt_id,
// key resolution, signature, no short-circuit, errors accumulate. `ours` is the
// AgentLair verifier's own order on the same bytes — key resolution, signature,
// receipt_id, short-circuit, one code and one stage. The second is reported so the
// two profiles' verdicts on identical bytes are directly comparable; it is not a
// claim about what APS requires. Where they disagree in shape, that disagreement
// is the point: sig-invalid and wrong-signer give this profile two different error
// lists and give ours the same single code, because receipt_id excludes signatures
// here and includes signer_did in agentlair-receipt/v1.
//
// Keys are regenerated from the published seed labels rather than read out of the
// fixture, and verification resolves to the regenerated bytes. A public key copied
// from the file it is meant to check is not an independent input.
//
// Usage: node agentlair-run.mjs [fixture.json] [--write]
// Exit 0 only when every vector, integrity stamp, chain root, cross-vector
// property and damage class behaves as expected. Exit 1 otherwise, including on a
// fixture too short to be the published set.

import { readFileSync, writeFileSync } from 'node:fs';
import {
  createHash,
  createPrivateKey,
  createPublicKey,
  verify as edVerify,
} from 'node:crypto';

// ── RFC 8785 JCS, string/object/array subset ────────────────────────────────────
// No Unicode normalization. RFC 8785 §3.1 requires components to preserve string
// data as is; the AgentLair canonicalizer normalized to NFC until 2026-08-05,
// which was a MUST-level deviation invisible while every corpus value is ASCII.
// Numbers throw rather than serialize: this profile's values are strings, and a
// silent number path is where a canonicalizer starts disagreeing with itself.
function jcs(value) {
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(jcs).join(',') + ']';
  if (value && typeof value === 'object') {
    // JS sorts by UTF-16 code unit, which is JCS's ordering rule.
    const keys = Object.keys(value).sort();
    return '{' + keys.map((k) => JSON.stringify(k) + ':' + jcs(value[k])).join(',') + '}';
  }
  throw new Error(`refusing to canonicalize ${typeof value} (${String(value)})`);
}

const omit = (o, ...ks) => Object.fromEntries(Object.entries(o).filter(([k]) => !ks.includes(k)));
const sha256hex = (buf) => createHash('sha256').update(buf).digest('hex');
const nulTag = (s) => Buffer.concat([Buffer.from(s, 'ascii'), Buffer.from([0x00])]);

// ── did:key (Ed25519, multicodec 0xed 0x01, base58btc) ─────────────────────────
const B58 = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';

function b58encode(bytes) {
  let n = 0n;
  for (const b of bytes) n = n * 256n + BigInt(b);
  let out = '';
  while (n > 0n) {
    out = B58[Number(n % 58n)] + out;
    n /= 58n;
  }
  for (const b of bytes) {
    if (b === 0) out = '1' + out;
    else break;
  }
  return out;
}

function didKeyFromRawPublic(raw) {
  if (raw.length !== 32) throw new Error(`Ed25519 public key must be 32 bytes, got ${raw.length}`);
  return 'did:key:z' + b58encode(Uint8Array.from([0xed, 0x01, ...raw]));
}

const SPKI_ED25519_PREFIX = Buffer.from('302a300506032b6570032100', 'hex');
const PKCS8_ED25519_PREFIX = Buffer.from('302e020100300506032b657004220420', 'hex');

const rawToPublicKey = (raw) =>
  createPublicKey({
    key: Buffer.concat([SPKI_ED25519_PREFIX, Buffer.from(raw)]),
    format: 'der',
    type: 'spki',
  });

/** seed = SHA-256(UTF8(label)), per the published seed convention. */
function keyFromSeedLabel(label) {
  const seed = createHash('sha256').update(Buffer.from(label, 'utf8')).digest();
  const priv = createPrivateKey({
    key: Buffer.concat([PKCS8_ED25519_PREFIX, seed]),
    format: 'der',
    type: 'pkcs8',
  });
  const der = createPublicKey(priv).export({ format: 'der', type: 'spki' });
  return { seedHex: seed.toString('hex'), pubRaw: Uint8Array.from(der.subarray(der.length - 32)) };
}

const SEED_LABELS = [
  'aeoess-aps-receipt-vectors-2026-08-05/key-a',
  'aeoess-aps-receipt-vectors-2026-08-05/key-b',
];

// ── the profile's constructions ────────────────────────────────────────────────
const apsReceiptId = (r) =>
  sha256hex(
    Buffer.concat([
      nulTag('APS-RECEIPT-ID-V1'),
      Buffer.from(jcs(omit(r, 'receipt_id', 'signatures')), 'utf8'),
    ]),
  );

const apsSigPreimage = (r, s) =>
  Buffer.concat([
    nulTag('APS-RECEIPT-SIG-V1'),
    Buffer.from(
      jcs({
        receipt: omit(r, 'signatures'),
        signer: { signer: s.signer, key_id: s.key_id, alg: s.alg },
      }),
      'utf8',
    ),
  ]);

const apsChainRoot = (chain) => sha256hex(Buffer.from(jcs(chain), 'utf8'));

// ── schema, both sets ──────────────────────────────────────────────────────────
// PUBLISHED is the member set as read from runners/aeoess_receipt_runner.py.
// INFERRED is what the 2026-08-05 run actually used: reconstructed from the
// published failure-code list before the repo runner was read, and wrong in two
// directions — it omits decision_ref from the allowed set, so a receipt carrying
// one would be rejected as an unknown field, and it omits delegation_ref and
// evidence_refs from the required set, so a receipt missing either would pass.
// Both are evaluated on every vector below and the agreement is recorded, so the
// claim "the divergence changes no verdict on this corpus" is measured here
// rather than asserted in prose.
const SCHEMAS = {
  published: {
    allowed: ['profile', 'receipt_id', 'receipt_type', 'issuer', 'subject_agent', 'action_ref',
      'delegation_ref', 'decision_ref', 'issued_at', 'evidence_refs', 'result', 'prev', 'signatures'],
    required: ['profile', 'receipt_id', 'receipt_type', 'issuer', 'subject_agent', 'action_ref',
      'delegation_ref', 'issued_at', 'evidence_refs', 'result', 'signatures'],
  },
  inferred: {
    allowed: ['profile', 'receipt_type', 'issuer', 'subject_agent', 'action_ref', 'delegation_ref',
      'issued_at', 'evidence_refs', 'result', 'prev', 'receipt_id', 'signatures'],
    required: ['profile', 'receipt_type', 'issuer', 'subject_agent', 'action_ref', 'issued_at',
      'result', 'receipt_id', 'signatures'],
  },
};

/** This profile's order: schema, receipt_id, key resolution, signature. No short-circuit. */
function verifyApsReceipt(r, resolveKey, schema = SCHEMAS.published) {
  const errors = [];
  const allowed = new Set(schema.allowed);
  for (const k of Object.keys(r)) if (!allowed.has(k)) errors.push(`ReceiptV1: unknown field ${k}`);
  for (const k of schema.required) if (!(k in r)) errors.push(`ReceiptV1: missing field ${k}`);
  if (r.profile !== 'aps-receipt-v1') errors.push('ReceiptV1: profile');

  let receipt_id_valid = false;
  try {
    receipt_id_valid = apsReceiptId(r) === r.receipt_id;
    if (!receipt_id_valid) errors.push('receipt_id_mismatch');
  } catch (e) {
    errors.push(`ReceiptV1: receipt_id (${e.message})`);
  }

  const signature_results = [];
  for (const s of r.signatures ?? []) {
    const pub = resolveKey(s.signer, s.key_id);
    if (!pub) {
      signature_results.push({ key_id: s.key_id, ok: false, reason: 'key_unresolved' });
      errors.push('key_unresolved');
      continue;
    }
    let ok = false;
    try {
      ok = edVerify(null, apsSigPreimage(r, s), rawToPublicKey(pub), Buffer.from(s.value, 'hex'));
    } catch {
      ok = false;
    }
    signature_results.push({ key_id: s.key_id, ok, reason: ok ? null : 'signature_invalid' });
    if (!ok) errors.push('signature_invalid');
  }
  return { valid: errors.length === 0, receipt_id_valid, signature_results, errors };
}

/** The AgentLair verifier's order on this envelope: keys, signature, receipt_id, short-circuit. */
function evaluateInAgentlairOrder(r, resolveKey) {
  try {
    jcs(omit(r, 'signatures'));
  } catch (e) {
    return { code: 'PROFILE_VIOLATION', stage: 'canonicalization', detail: e.message };
  }
  const sigs = r.signatures ?? [];
  if (!sigs.length) return { code: 'SIGNATURE_MISSING', stage: 'signature', detail: 'no signatures' };
  for (const s of sigs) {
    const pub = resolveKey(s.signer, s.key_id);
    if (!pub) return { code: 'DID_URI_INVALID', stage: 'key_resolution', detail: `unresolved ${s.key_id}` };
    let ok = false;
    try {
      ok = edVerify(null, apsSigPreimage(r, s), rawToPublicKey(pub), Buffer.from(s.value, 'hex'));
    } catch {
      ok = false;
    }
    if (!ok) return { code: 'SIGNATURE_INVALID', stage: 'signature', detail: `verify failed for ${s.key_id}` };
  }
  if (apsReceiptId(r) !== r.receipt_id)
    return { code: 'RECEIPT_ID_MISMATCH', stage: 'receipt_id', detail: `declared ${r.receipt_id}` };
  return { code: 'OK', stage: 'none', detail: 'signatures valid, receipt_id reproduces' };
}

// ── run ────────────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const write = args.includes('--write');
const fixturePath =
  args.find((a) => !a.startsWith('--')) ??
  new URL('receipts-aeoess-2026-08-05.json', import.meta.url).pathname;

const fixtureBytes = readFileSync(fixturePath);
const doc = JSON.parse(fixtureBytes.toString('utf8'));
const vectors = doc.vectors ?? [];

// Minimum-expected-input floor. A runner that prints a clean summary over zero
// vectors is false-clean by construction, and that is exactly the shape a broken
// path takes when it still exits 0.
if (vectors.length < 6) {
  console.error(`FLOOR: expected at least 6 vectors, got ${vectors.length} — refusing to report a pass`);
  process.exit(1);
}

let bad = 0;
const report = {
  fixture: 'fixtures/cross-stack/receipts-aeoess/receipts-aeoess-2026-08-05.json',
  fixture_sha256: sha256hex(fixtureBytes),
  fixture_commit: '5da275b3b86244e19a2f6e085b14fb205dd8331e',
  fixture_blob_sha: '088e384e618238208d36173dba01d56e322668d1',
  schema: doc.schema,
  authored_at: doc.authored_at,
  runner: 'fixtures/cross-stack/receipts-aeoess/agentlair-run.mjs (AgentLair, stdlib only)',
  node: process.version,
  first_run_at: '2026-08-05T18:18:00Z',
  first_run_note:
    'The 2026-08-05 run was reported in mail and used the inferred member set; this file is the same evidence regenerated by the shipped runner under both member sets.',
  ran_at: new Date().toISOString(),
  keys: [],
  vectors: [],
};

console.log(`fixture ${fixturePath}`);
console.log(`sha256  ${report.fixture_sha256}`);
console.log('');
console.log('KEY REGENERATION FROM PUBLISHED SEED LABELS');

const table = new Map();
const published = doc.profile?.keys ?? [];
if (published.length < 2) {
  console.error(`FLOOR: expected at least 2 published keys, got ${published.length}`);
  process.exit(1);
}
const regen = SEED_LABELS.map(keyFromSeedLabel);
for (const [i, k] of published.entries()) {
  const r = regen[i];
  const hexOk = !!r && Buffer.from(r.pubRaw).toString('hex') === k.public_key_hex;
  const didOk = !!r && didKeyFromRawPublic(r.pubRaw) === k.did_key;
  if (!hexOk || !didOk) bad++;
  console.log(`  ${hexOk && didOk ? 'OK  ' : 'FAIL'}  ${SEED_LABELS[i]}`);
  console.log(`          seed sha256 ${r?.seedHex}`);
  console.log(`          public key ${hexOk ? 'matches' : 'DIFFERS from'} published hex; did:key ${didOk ? 'matches' : 'DIFFERS'}`);
  report.keys.push({
    key_id: k.key_id,
    seed_label: SEED_LABELS[i],
    seed_sha256: r?.seedHex,
    pub_hex_match: hexOk,
    did_key_match: didOk,
  });
  if (r) table.set(`${k.signer} ${k.key_id}`, r.pubRaw); // regenerated bytes, not the fixture's
}
const resolveKey = (signer, keyId) => table.get(`${signer} ${keyId}`);

console.log('');
console.log('PER-VECTOR');
let schemaAgreement = true;
for (const v of vectors) {
  const res = verifyApsReceipt(v.receipt, resolveKey, SCHEMAS.published);
  const alt = verifyApsReceipt(v.receipt, resolveKey, SCHEMAS.inferred);
  const agree = res.valid === alt.valid && res.errors.length === alt.errors.length &&
    res.errors.every((e) => alt.errors.includes(e));
  if (!agree) schemaAgreement = false;

  const ours = evaluateInAgentlairOrder(v.receipt, resolveKey);
  const observed = res.valid ? 'valid' : 'invalid';
  const wire = JSON.stringify(v.receipt); // published member order, compact
  const lenOk = v.receipt_len === undefined || v.receipt_len === wire.length;
  const shaOk = v.receipt_sha256 === undefined || v.receipt_sha256 === sha256hex(Buffer.from(wire, 'utf8'));
  const expErrs = v.expected_errors ?? [];
  const errsOk = expErrs.length === res.errors.length && expErrs.every((e) => res.errors.includes(e));
  const chainOk = v.delegation_chain ? apsChainRoot(v.delegation_chain) === v.delegation_chain_root : true;
  const pass = observed === v.expected_result && errsOk && lenOk && shaOk && chainOk && agree;
  if (!pass) bad++;

  console.log(`  ${pass ? 'OK  ' : 'FAIL'}  ${v.id}`);
  console.log(`          theirs: ${observed} errors=[${res.errors.join(', ')}] (expected [${expErrs.join(', ')}])`);
  console.log(`          ours:   ${ours.code === 'OK' ? 'valid' : 'invalid'}/${ours.code} at ${ours.stage}`);
  console.log(`          stamp:  len ${lenOk ? 'ok' : 'MISMATCH'}, sha256 ${shaOk ? 'ok' : 'MISMATCH'}${v.delegation_chain ? `, chain_root ${chainOk ? 'ok' : 'MISMATCH'}` : ''}`);

  report.vectors.push({
    id: v.id,
    expected_result: v.expected_result,
    expected_errors: expErrs,
    observed_result: observed,
    observed_errors: res.errors,
    receipt_id_valid: res.receipt_id_valid,
    signature_results: res.signature_results,
    agentlair_order: ours,
    integrity: { len_ok: lenOk, sha256_ok: shaOk },
    chain_root_ok: v.delegation_chain ? chainOk : null,
    schema_sets_agree: agree,
    pass,
  });
}
report.schema_sets_agree = schemaAgreement;
console.log(`  ${schemaAgreement ? 'OK  ' : 'FAIL'}  member-set divergence changes no verdict on this corpus (published vs inferred)`);
if (!schemaAgreement) bad++;

// ── the cross-vector property SOURCE.md asserts ────────────────────────────────
const val = vectors.find((v) => v.id.endsWith('-valid'));
const rev = vectors.find((v) => v.id.endsWith('-key-order-reversed'));
if (val && rev) {
  const sameCanon = jcs(omit(val.receipt, 'signatures')) === jcs(omit(rev.receipt, 'signatures'));
  const sameSig = val.receipt.signatures[0].value === rev.receipt.signatures[0].value;
  const diffWire = val.receipt_sha256 !== rev.receipt_sha256;
  const ok = sameCanon && sameSig && diffWire;
  if (!ok) bad++;
  console.log('');
  console.log('CROSS-VECTOR');
  console.log(`  ${ok ? 'OK  ' : 'FAIL'}  key-order-reversed shares canonical bytes and signature with valid, differs on wire digest`);
  report.cross_vector = { same_canonical: sameCanon, same_signature: sameSig, different_wire_sha256: diffWire };
}

// ── damage classes ─────────────────────────────────────────────────────────────
// A positive run means nothing until the runner is shown to still go red. These
// six are applied to a copy of the valid vector, never to the fixture on disk.
console.log('');
console.log('DAMAGE CLASSES (applied to a copy of the valid vector)');
const base = JSON.parse(JSON.stringify(val.receipt));
const damage = [
  ['content mutated after signing', () => ({ ...base, delegation_ref: base.delegation_ref.replace(/.$/, '0') })],
  ['signature byte corrupted', () => ({ ...base, signatures: [{ ...base.signatures[0], value: base.signatures[0].value.replace(/.$/, '0') }] })],
  ['declared receipt_id corrupted', () => ({ ...base, receipt_id: base.receipt_id.replace(/.$/, '0') })],
  ['unknown member added (closed schema)', () => ({ ...base, delegation_chain_root: 'deadbeef' })],
  ['key_id swapped to the non-signing key', () => ({ ...base, signatures: [{ ...base.signatures[0], key_id: base.signatures[0].key_id.replace(/#k1$/, '#k2') }] })],
  ['signer absent from the key table', () => ({ ...base, signatures: [{ ...base.signatures[0], signer: 'did:key:z6MkNOSUCHSIGNER' }] })],
];
let caught = 0;
const damageRows = [];
for (const [name, mutate] of damage) {
  const res = verifyApsReceipt(mutate(), resolveKey, SCHEMAS.published);
  const red = !res.valid;
  if (red) caught++;
  else bad++;
  console.log(`  ${red ? 'CAUGHT' : 'MISSED'}  ${name}${red ? ` -> [${res.errors.join(', ')}]` : ''}`);
  damageRows.push({ name, caught: red, errors: res.errors });
}
report.redteam = { classes: damage.length, caught, detail: damageRows };
report.failures = bad;

console.log('');
console.log(
  bad === 0
    ? `SUMMARY: ${vectors.length}/${vectors.length} vectors match expectation, ${caught}/${damage.length} damage classes caught, 0 failures`
    : `SUMMARY: ${bad} check(s) FAILED`,
);

if (write) {
  const out = new URL('agentlair-run-2026-08-05.json', import.meta.url).pathname;
  writeFileSync(out, JSON.stringify(report, null, 2) + '\n');
  console.log(`report -> ${out}`);
}

process.exit(bad === 0 ? 0 : 1);
