"""Generate the synthetic lower-bound regression fixture.

Deterministic: the signing key comes from a fixed 32-byte seed recorded here,
so the fixture is regenerable byte-for-byte by anyone. The private half has no
value beyond producing this fixture and is deliberately published.

Replaces the reconstructed 2026-07-29 AS-RECEIVED drop as the regression
oracle. That drop was the issuer's, and he corrected it 57 minutes later. A
synthetic token we control can be regenerated, rotated and explained without a
reader having to work out which of two mails was canonical.
"""

import base64, hashlib, json, pathlib
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

SEED = bytes(range(32))  # 000102...1f, fixed and published on purpose
sk = Ed25519PrivateKey.from_private_bytes(SEED)
pk = sk.public_key()
raw_pub = pk.public_bytes_raw()

def b64u(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).decode().rstrip("=")

kid = hashlib.sha256(raw_pub).hexdigest()[:8]
JWKS = {"keys": [{"kty": "OKP", "crv": "Ed25519", "alg": "EdDSA", "kid": kid, "x": b64u(raw_pub)}]}

def mint(iat: int, exp: int, jti: str) -> str:
    header = {"alg": "EdDSA", "typ": "JWT", "kid": kid}
    payload = {
        "iss": "https://synthetic.invalid",
        "sub": "acc_syntheticRegression",
        "aud": "https://synthetic.invalid/verify",
        "iat": iat, "exp": exp, "jti": jti,
        "al_scopes": ["aps:conformance:regression"],
        "al_name": "synthetic-regression",
        "al_nid": "did:key:z6MkgRmUXtGdTkXhAcfpoabEyvZEjsdvTnGw6gaX3LcSdhhj",
    }
    h = b64u(json.dumps(header, separators=(",", ":")).encode())
    p = b64u(json.dumps(payload, separators=(",", ":")).encode())
    sig = b64u(sk.sign((h + "." + p).encode()))
    return h + "." + p + "." + sig

# Fixed instants. IAT is the lower bound the oracle exists to exercise.
IAT, EXP = 1785340800, 1785344400          # 2026-07-29T16:00:00Z .. 17:00:00Z
OLD_IAT, OLD_EXP = 1784714400, 1784718000  # 2026-07-22T10:00:00Z .. 11:00:00Z

live = mint(IAT, EXP, "syn_liveRegression01")
old = mint(OLD_IAT, OLD_EXP, "syn_expiredRegressn")

def stamp(v):
    v["token_len"] = len(v["aat"])
    v["token_sha256"] = hashlib.sha256(v["aat"].encode("utf-8")).hexdigest()
    return v

doc = {
 "schema": "aat-pair-v1",
 "schema_note": (
   "SYNTHETIC regression oracle. Three vectors: a positive, an upper-bound negative, "
   "and a lower-bound negative that reuses the positive's exact bytes with only "
   "verification_time moved below notBefore. A runner that checks only the upper "
   "window bound reports this fixture clean, which is the property the suite asserts."),
 "provenance": (
   "Generated by runners/generate_synthetic_regression.py from a fixed published seed. "
   "Regenerable byte-for-byte. Contains no issuer material and requires no network."),
 "integrity_convention": "token_len + token_sha256 over utf8 of the compact JWT, hex",
 "issuer": "synthetic",
 "issuer_jwks": {"inline": True, "kid": kid, "alg": "EdDSA"},
 "authored_at": "2026-07-29T16:00:01Z",
 "vectors": [
   stamp({"id": "syn-regression-live", "aat": live,
     "notBefore": "2026-07-29T16:00:00Z", "notAfter": "2026-07-29T17:00:00Z",
     "verification_time": "2026-07-29T16:00:01Z", "expected_result": "valid",
     "verifier_must": "validate signature against the inline key, then check BOTH window bounds at verification_time"}),
   stamp({"id": "syn-regression-expired", "aat": old,
     "expiredAt": "2026-07-22T11:00:00Z",
     "verification_time": "2026-07-29T16:00:01Z", "expected_result": "exp_reject",
     "expected_failure_stage": "window_check", "expected_reason": "expired before verification time",
     "verifier_must": "reject at the window check; a valid signature does not rescue an expired token"}),
   stamp({"id": "syn-regression-not-yet-valid", "aat": live,
     "notBefore": "2026-07-29T16:00:00Z", "notAfter": "2026-07-29T17:00:00Z",
     "verification_time": "2026-07-29T15:59:00Z", "expected_result": "nbf_reject",
     "expected_failure_stage": "window_check", "expected_reason": "not yet valid at verification_time",
     "vector_note": "Same token bytes as syn-regression-live. Only verification_time differs, at notBefore minus 60s, so the lower bound is the only thing that can change the outcome. jti repeats deliberately.",
     "verifier_must": "reject at the window check because verification_time is below notBefore"}),
 ],
}

base = pathlib.Path(__file__).resolve().parent.parent
(base / "fixtures/cross-stack/synthetic/aat-synthetic-regression.json").parent.mkdir(parents=True, exist_ok=True)
(base / "fixtures/cross-stack/synthetic/aat-synthetic-regression.json").write_text(
    json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
(base / "runners/issuers/synthetic.json").write_text(json.dumps({
 "name": "synthetic",
 "jwks_inline": JWKS,
 "kid": kid,
 "alg": "EdDSA",
 "note": "Synthetic regression issuer. Key derived from a fixed published seed in runners/generate_synthetic_regression.py. No network, no third-party dependency.",
}, indent=2) + "\n", encoding="utf-8")

print("kid:", kid)
print("wrote fixtures/cross-stack/synthetic/aat-synthetic-regression.json")
print("wrote runners/issuers/synthetic.json")
